dist: focal

language: python
python:
  - 3.9
  - 3.8
  - 3.7
  - 3.6

install:
 - pip install --upgrade pip
 - pip install black codecov coverage isort flake8
 - pip install -q "Django$DJANGO_VERSION"
 - pip install -e .

env:
  matrix:
   - DJANGO_VERSION=">=2.2,<3"
   - DJANGO_VERSION=">=3.2,<4"

script:
 - black --check .
 - flake8 --max-line-length=88 .
 - isort --recursive --check-only --diff *.py django_spreadsheet tests
 - coverage run --include="./*" --omit="docs/","*/tests/*","*/tests.py","setup.py" -m unittest -v

after_success:
 - codecov
