name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        django-version: [">=3.2,<4", ">=4.2,<5"]
        exclude:
          - python-version: "3.13"
            django-version: ">=3.2,<4"
        include:
          - python-version: "3.13"
            django-version: ">=4.2,<5"
            include-codecov: true

    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Create and activate venv
      run: |
        python -m venv ~/.venv
        source ~/.venv/bin/activate
        pip install -U pip 'setuptools>=61'

    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        source ~/.venv/bin/activate
        pip install coverage isort flake8 'black<25' twine setuptools build
        pip install "django${{ matrix.django-version }}"
        pip install -e .

    - name: Run Tests
      run: |
        source ~/.venv/bin/activate
        black --check .
        flake8 --max-line-length=88 .
        isort --check-only --diff --profile=black *.py .
        python -m build
        twine check dist/*
        coverage run --include="./*" --omit="docs/","*/tests/*","_version.py" -m unittest -v
        coverage json

    - name: Upload coverage to Codecov
      if: matrix.include-codecov == true
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
